### ISSUE TITLE
Documentation for lib is not available due to lack of LICENSE (or similar) file.

### ISSUE THREAD

**Issue by eleksir** [meinside/telegram-bot-go#5]
Docs at pkg.go.dev is hidden and notice about incompatibility is displayed. Please take a look at https://pkg.go.dev/github.com/meinside/telegram-bot-go?utm_source=godoc

https://pkg.go.dev/license-policy refer to their license check policy and choose name for license file :)

**Comment by meinside** [comment]
Thanks for pointing it out! :-) I'll create a separated license file for that.
